name: Update docs

on:
  workflow_dispatch:
  gollum:
  workflow_run:
    workflows: ["Update API Changelog"]
    branches: [main]
    types:
      - completed

jobs:
  docs: 
    runs-on: arc-runner-k8s
    permissions: write-all
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ${{ github.repository_owner }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: unipoll/docs
          event-type: update_submodules