name: Label Issues

on:
  issues:
    types:
      - reopened
      - opened
      - edited
jobs:
  label_issues:
    # runs-on: ubuntu-latest
    runs-on: arc-runner-k8s
    permissions:
      issues: write
      contents: read
    steps:
    - uses: github/issue-labeler@v3.2
      with:
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        include-title: 1
        include-body: 0
        sync-labels: 1
        repo-token: ${{ github.token }}