name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: arc-runner-k8s
    strategy:
      matrix:
        python-version: ['3.11']
    environment:
      name: pypi
      url: https://pypi.org/p/unipoll-api
    permissions:
      id-token: write
    steps:
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install build
    - name: Download source code
      uses: actions/checkout@v3
    - name: Build package distributions
      run: |
        python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        username: "__token__"
        password: ${{ secrets.PYPI_TOKEN }}
