name: Run tests with Tox 

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "development"

jobs:
  test:
    # runs-on: ${{matrix.os}}
    # runs-on: self-hosted
    runs-on: arc-runner-k8s
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11'] 
        node-version: [18.x] 
        mongodb-version: ['6.0'] 
    steps:
      - name: Force Install GIT latest
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git
          echo "GIT Version: $(git --version)"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions --root-user-action=ignore
      
      - name: Test with tox
        run: |
          tox run

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
